name: Lint & Test
on:
  pull_request:
    branches: [main, development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo 🏨
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
          cache: 'bun'

      - name: Install packages
        run: bun install

      - name: Check Lint
        run: bun lint
      
